### ISSUE TITLE
Cannot connect to host MonogDB in Docker container

### ISSUE THREAD

**Issue by legend620** [sidhantpanda/docker-express-typescript-boilerplate#124]
Can not connect to MongoDB at mongodb://host.docker.internal:27017/books

I just run `docker-compose up -d` on the MongoDB installed AWS EC2 instance.

**Comment by sidhantpanda** [comment]
You can use `yarn dev` to start the development server.

The mongo container definition is not in `docker-compose.yml` but instead, it is present in [`docker-compose.dev.yml`](https://github.com/sidhantpanda/docker-express-typescript-boilerplate/blob/master/docker-compose.dev.yml).
