### ISSUE TITLE
Project assumes nodemon and ts-node are installed globally

### ISSUE THREAD

**Issue by RazerMoon** [sidhantpanda/docker-express-typescript-boilerplate#15]
Hi, really like the project but I had a couple of issues.

dev.sh throws errors:
```bash
./scripts/dev.sh: line 25: nodemon: command not found
```
```bash
'ts-node' is not recognized as an internal or external command
```

Maybe include a notice in the README or add a script to `package.json` and add `ts-node` to devDependencies?

**Comment by sidhantpanda** [comment]
Hey @RazerMoon ,

Fixed this with https://github.com/sidhantpanda/docker-express-typescript-boilerplate/commit/3a0bd4b28047e9ad6443ae285663d80c125667b5
