### ISSUE TITLE
License

### ISSUE THREAD

**Issue by andrewpat24** [sidhantpanda/docker-express-typescript-boilerplate#4]
Love the boilerplate! Could you put an MIT license on this?

**Comment by sidhantpanda** [comment]
Sure, but why an MIT license? Just curious about all the licenses

**Comment by andrewpat24** [comment]
It's pretty much the typical license used so people aren't scared to use your code since it's essentially "do whatever the hell you want, open or closed source, we don't care"

But check this site out to find out more! 

https://choosealicense.com/

**Comment by sidhantpanda** [comment]
Done! Thanks :)
