### ISSUE TITLE
ctrl + s doesn't  restart the services

### ISSUE THREAD

**Issue by Manishkini** [sidhantpanda/docker-express-typescript-boilerplate#9]
After `Ctrl + S` it saves the document but it needs to do `npm run build && npm run start` to run the updated code.. its takes lot of time to run the command again and again

**Comment by sidhantpanda** [comment]
Hi @Manishkini , the server has hot reloading enabled. When you start with `npm run dev`, a Mongo docker container is created and a nodemon process is started.

Dev Startup Script: https://github.com/sidhantpanda/docker-express-typescript-boilerplate/blob/master/scripts/dev.sh
Nodemon Config: https://github.com/sidhantpanda/docker-express-typescript-boilerplate/blob/master/nodemon.json
